name: Levantar Node

on: push

jobs:
    checkOut:
        runs-on: ubuntu-20.04

        steps:
            - name: Check-Out del código
              uses: actions/checkout@v4

            - name: Revisar url
              run: echo "Ruta del directorio es $GITHUB_WORKSPACE"

            - name: Listar archivos
              run: ls -la $GITHUB_WORKSPACE

            - name: Instalar dependencias
              run: npm i

            - name: Ejecutar backend
              run: npm run dev