name: Levantar Node

on: [push]

jobs:
  checkOut:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node_version: [18.x, 20.x]

    steps:
      - name: Check-Out del código
        uses: actions/checkout@v4
      - run: node --version

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - run: node --version

      - name: Revisar url
        run: echo "Ruta del directorio es $GITHUB_WORKSPACE"

      - name: Listar archivos
        run: ls -la $GITHUB_WORKSPACE

      - name: Instalar dependencias
        run: npm i

      - name: Pruebas en Prettier
        run: npx prettier . --check
