name: Levantar Node

on: [push]

jobs:
    checkOut:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            node_version: [18.x, 20.x]

        steps:
            - name: Check-Out del código
              uses: actions/checkout@v4
            - run: node --version

            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node_version }}

            - run: node --version

            - name: Revisar url
              run: echo "Ruta del directorio es $GITHUB_WORKSPACE"

            - name: Listar archivos
              run: ls -la $GITHUB_WORKSPACE              
              
            - name: Correr ante error
              if: ${{ failure() }}
              run: echo "Error"
              continue-on-error: true

            - name: Instalar dependencias
              run: npm i
            
            - name: Mostrar Secret
              run: echo ${{ vars.MI_VARIABLE }}
