name: Decir Hola Mundo

on: [push]

jobs:

  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Decir Hola
        run: echo "Hola Mundo de HaB"
      - name: Pausa
        run: sleep 5

  saludar2:
    runs-on: ubuntu-latest
    steps:
      - name: Decir Hola
        run: echo "Hola Mundo de HaB"
      - name: Pausa
        run: sleep 5

  darHora:
    runs-on:  ubuntu-latest
    needs: saludar
    steps:        
      - name: Que hora es
        run: echo "La hora del servidor es $(date)"

  despedir:
    runs-on: ubuntu-latest
    needs: saludar2
    steps:
      - name: Decir Chau
        run: echo "Chau Mundo de HaB"

