name: Decir Hola Mundo

on: [push]

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Decir Hola
        run: echo "Hola Mundo de HaB"
  despedir:
    runs-on: ubuntu-latest
    steps:
      - name: Decir Chau
        run: echo "Chau Mundo de HaB"

