name: Decir Hola Mundo

on:
  push:
    branches: [dev]

jobs:

  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Decir Hola
        run: echo "Hola Mundo de HaB"
      - name: Pausa
        run: sleep 2
      - name: Que hora es
        run: echo "La hora del servidor es $(date)"

  despedir:
    runs-on: ubuntu-latest
    steps:
      - name: Decir Chau
        run: echo "Chau Mundo de HaB"

